# Generated by Django 4.2.3 on 2023-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0008_alter_product_stocks'),
        ('cart', '0002_rename_car_id_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(null=True, to='catagorie.varients'),
        ),
    ]
