# Generated by Django 4.2.3 on 2023-10-30 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0008_alter_product_stocks'),
        ('cart', '0003_remove_cartitem_variations_cartitem_variations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variations',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catagorie.varients'),
        ),
    ]
