# Generated by Django 4.2.3 on 2023-11-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_coupon_redeemedcoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeemedcoupon',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
    ]
