# Generated by Django 4.2.3 on 2023-11-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_redeemedcoupon_is_redeemed'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='Usage_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coupon',
            name='maximum_purchase_value',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_purchase_value',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
