# Generated by Django 4.2.3 on 2023-11-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_banner_images_delete_image_banner_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='images',
            field=models.ImageField(upload_to='banner_images/'),
        ),
    ]
