# Generated by Django 4.2.3 on 2023-11-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_banner_images_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='set',
            field=models.BooleanField(default=False),
        ),
    ]
