# Generated by Django 4.2.3 on 2023-10-14 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
