# Generated by Django 4.2.3 on 2023-10-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0003_alter_category_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
