# Generated by Django 4.2.6 on 2023-10-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0006_alter_product_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='varients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varation_catagory', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('color', models.CharField(choices=[('white', 'black'), ('blue', 'blue'), ('black', 'black'), ('red', 'red')], max_length=100)),
                ('size', models.PositiveIntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catagorie.product')),
            ],
        ),
    ]
