# Generated by Django 4.2.6 on 2023-11-13 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0008_alter_product_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stocks',
        ),
        migrations.AddField(
            model_name='varients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='varients',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varients',
            name='color',
            field=models.CharField(choices=[('white', 'white'), ('blue', 'blue'), ('black', 'black'), ('red', 'red')], max_length=100),
        ),
        migrations.CreateModel(
            name='varientImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='photos/productvarient')),
                ('varients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catagorie.varients')),
            ],
        ),
    ]
