# Generated by Django 4.2.3 on 2023-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0011_alter_product_price_alter_product_rprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
