# Generated by Django 4.2.3 on 2023-11-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0012_alter_varients_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='varients_images/'),
        ),
    ]
