# Generated by Django 4.2.3 on 2023-11-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagorie', '0014_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
