# Generated by Django 4.2.3 on 2023-11-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
